last_change = 2026-09-24T17:36:17.824255Z
addr = 0x46960
size = 0xa9f
name = "CNetworkGameClient_ProcessPacketEntitiesInternal"
type = "char"

[header]
name = "CNetworkGameClient_ProcessPacketEntitiesInternal"
addr = 0x46960
type = "char"

[header.args]
