last_change = 2026-09-24T17:36:17.857760Z
addr = 0x5b180
size = 0x126
name = "CNetworkClientSpawnGroupCreatePrerequisites_Init"
type = "unsigned long long"

[header]
name = "CNetworkClientSpawnGroupCreatePrerequisites_Init"
addr = 0x5b180
type = "unsigned long long"

[header.args]
