last_change = 2026-09-24T17:36:15.626659Z
addr = 0x670b0
size = 0x39b
name = "CNetworkGameClient_ProcessClassInfo"
type = "char"

[header]
name = "CNetworkGameClient_ProcessClassInfo"
addr = 0x670b0
type = "char"

[header.args]
