last_change = 2026-09-24T17:36:15.626686Z
addr = 0x74390
size = 0x12
name = "CEngineServer_ShowFrameTimeReport"
type = "double"

[header]
name = "CEngineServer_ShowFrameTimeReport"
addr = 0x74390
type = "double"

[header.args]
