last_change = 2026-09-24T17:36:15.626705Z
addr = 0x74e80
size = 0x1b
name = "CEngineClient_IsPlayingDemo"
type = "char"

[header]
name = "CEngineClient_IsPlayingDemo"
addr = 0x74e80
type = "char"

[header.args]
