last_change = 2026-09-24T17:36:15.626684Z
addr = 0x742b0
size = 0x8
name = "CEngineServer_GetFrameTimeAmnesty"
type = "const char *"

[header]
name = "CEngineServer_GetFrameTimeAmnesty"
addr = 0x742b0
type = "const char *"

[header.args]
