last_change = 2026-09-24T17:36:15.626677Z
addr = 0x72660
size = 0xb4
name = "CEngineServer_GetSteamUniverse"
type = "long long"

[header]
name = "CEngineServer_GetSteamUniverse"
addr = 0x72660
type = "long long"

[header.args]
