last_change = 2026-09-24T17:36:15.626821Z
addr = 0x88a40
size = 0x161
name = "CNetworkGameClientBase_ProcessCmdKeyValues"
type = "char"

[header]
name = "CNetworkGameClientBase_ProcessCmdKeyValues"
addr = 0x88a40
type = "char"

[header.args]
