last_change = 2026-09-24T17:36:15.626840Z
addr = 0x9c4a0
size = 0x1e3
name = "CNetworkGameServer_IsPausable"
type = "bool"

[header]
name = "CNetworkGameServer_IsPausable"
addr = 0x9c4a0
type = "bool"

[header.args]
