last_change = 2026-09-24T17:36:15.626914Z
addr = 0xa1680
size = 0x4e
name = "CEngineServer_GetClientSteamID"
type = "long long"

[header]
name = "CEngineServer_GetClientSteamID"
addr = 0xa1680
type = "long long"

[header.args]
