last_change = 2026-09-24T17:36:15.626895Z
addr = 0xa0a50
size = 0x33
name = "CEngineServer_GetPlayerNetInfo"
type = "long long"

[header]
name = "CEngineServer_GetPlayerNetInfo"
addr = 0xa0a50
type = "long long"

[header.args]
