last_change = 2026-09-24T17:36:18.506791Z
addr = 0xa10b0
size = 0x4f
name = "CEngineServer_PrecacheGeneric"
type = "long long"

[header]
name = "CEngineServer_PrecacheGeneric"
addr = 0xa10b0
type = "long long"

[header.args]
