last_change = 2026-09-24T17:36:15.626916Z
addr = 0xa1730
size = 0x17
name = "CEngineServer_GetServerGlobals"
type = "long long"

[header]
name = "CEngineServer_GetServerGlobals"
addr = 0xa1730
type = "long long"

[header.args]
