last_change = 2026-09-24T17:36:18.738724Z
addr = 0xafd10
size = 0x3e5
name = "CNetworkGameServerBase_BroadcastMessage"
type = "long long"

[header]
name = "CNetworkGameServerBase_BroadcastMessage"
addr = 0xafd10
type = "long long"

[header.args]
