last_change = 2026-09-24T17:36:15.626981Z
addr = 0xb3660
size = 0x9
name = "CNetworkGameServerBase_GetTimescale"
type = "float"

[header]
name = "CNetworkGameServerBase_GetTimescale"
addr = 0xb3660
type = "float"

[header.args]
