last_change = 2026-09-24T17:36:15.626976Z
addr = 0xb2110
size = 0x7
name = "CNetworkGameServerBase_GetMaxClients"
type = "long long"

[header]
name = "CNetworkGameServerBase_GetMaxClients"
addr = 0xb2110
type = "long long"

[header.args]
