last_change = 2026-09-24T17:36:15.626978Z
addr = 0xb34a0
size = 0x164
name = "CNetworkGameServerBase_IsSaveRestoreAllowed"
type = "char"

[header]
name = "CNetworkGameServerBase_IsSaveRestoreAllowed"
addr = 0xb34a0
type = "char"

[header.args]
