last_change = 2026-09-24T17:36:18.854509Z
addr = 0xb4f30
size = 0x34f
name = "CNetworkGameServerBase_ServerSimulate"
type = "void"

[header]
name = "CNetworkGameServerBase_ServerSimulate"
addr = 0xb4f30
type = "void"

[header.args]
