last_change = 2026-09-24T17:36:15.627001Z
addr = 0xb4eb0
size = 0x72
name = "CNetworkGameServerBase_ServerProcessNetworking"
type = "void"

[header]
name = "CNetworkGameServerBase_ServerProcessNetworking"
addr = 0xb4eb0
type = "void"

[header.args]
