last_change = 2026-09-24T17:36:15.626985Z
addr = 0xb3950
size = 0x13d
name = "CNetworkGameServerBase_KickClient"
type = "void"

[header]
name = "CNetworkGameServerBase_KickClient"
addr = 0xb3950
type = "void"

[header.args]
