last_change = 2026-09-24T17:36:15.627156Z
addr = 0x1c4cb0
size = 0x502
name = "CInputService_ProcessCommandBuffer"
type = "void"

[header]
name = "CInputService_ProcessCommandBuffer"
addr = 0x1c4cb0
type = "void"

[header.args]
