last_change = 2026-09-24T17:36:15.627163Z
addr = 0x1cefc0
size = 0xe
name = "CNetworkClientService_RegisterEventMap"
type = "void"

[header]
name = "CNetworkClientService_RegisterEventMap"
addr = 0x1cefc0
type = "void"

[header.args]
