last_change = 2026-09-24T17:36:15.627186Z
addr = 0x1d3dc0
size = 0x19
name = "CNetworkClientService_OnClientPauseSimulate"
type = "long long"

[header]
name = "CNetworkClientService_OnClientPauseSimulate"
addr = 0x1d3dc0
type = "long long"

[header.args]
