last_change = 2026-09-24T17:36:19.709628Z
addr = 0x1dd960
size = 0x7d
name = "CWaitForInitialSpawnGroupsPrerequisite_GetStatus"
type = "long long"

[header]
name = "CWaitForInitialSpawnGroupsPrerequisite_GetStatus"
addr = 0x1dd960
type = "long long"

[header.args]
