last_change = 2026-09-24T17:36:15.627175Z
addr = 0x1d38f0
size = 0x16e
name = "CNetworkClientService_OnClientAdvanceTick"
type = "long long"

[header]
name = "CNetworkClientService_OnClientAdvanceTick"
addr = 0x1d38f0
type = "long long"

[header.args]
