last_change = 2026-09-24T17:36:15.627294Z
addr = 0x1e2960
size = 0x93
name = "CNetworkServerService_OnKickByIdHLTV"
type = "void"

[header]
name = "CNetworkServerService_OnKickByIdHLTV"
addr = 0x1e2960
type = "void"

[header.args]
