last_change = 2026-09-24T17:36:15.627287Z
addr = 0x1e20e0
size = 0x78
name = "CNetworkServerService_SetGameLoadStarted"
type = "char"

[header]
name = "CNetworkServerService_SetGameLoadStarted"
addr = 0x1e20e0
type = "char"

[header.args]
