last_change = 2026-09-24T17:36:20.024618Z
addr = 0x210a00
size = 0x2a0
name = "CEngineServiceMgr_DeactivateLoop"
type = "long long"

[header]
name = "CEngineServiceMgr_DeactivateLoop"
addr = 0x210a00
type = "long long"

[header.args]
