last_change = 2026-09-24T17:36:20.181380Z
addr = 0x224160
size = 0x2d6
name = "CLoopTypeClientServer_LoopTypeInit"
type = "char"

[header]
name = "CLoopTypeClientServer_LoopTypeInit"
addr = 0x224160
type = "char"

[header.args]
